### ISSUE TITLE
Error while building echo_master_service due to missing file in module json2pojo

### ISSUE THREAD

**Issue by skmonga** [dream-lab/echo#10] opened 2018-01-06 14:05 UTC
I was trying to build echo_master_service but it fails due to a failure in building the module json2pojo. The **json2pojo** module uses **jsonschema2pojo-maven-plugin** plugin to create pojo classes from the schema located under json2pojo/src/main/resources/schema. This directory contains two files : dataflow_input and wire. The **dataflow_input** file has the following content 

{
  "$schema": "http://json-schema.org/schema#",
  "#id": "http://dream-lab.in/dataflow_input.json",
  "type": "object",
  "properties": {
    "processors": {
      "type": "array",
      "minItems": 1,
      "items": {"$ref": "processor"},
      "uniqueItems": true
    },
    "wiring": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "wire"
      },
      "uniqueItems": true
    },
    "inputstreams": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "string"
      },
      "uniqueItems": true
    },
    "QOS": {
      "type": "number"
    }
  }
}

 wherein the processors field has a reference to processor but there exists no file of that name while the same works for wiring as there is a file of name wire. Am i getting this wrong or this is only related to the missing file ?

**Comment by aakashkhochare** [comment] 2018-01-06 19:13
I have been able to replicate the issue and yes, the missing file is the cause. @pushkar1593  `2f1e54e` has 11 deletions which includes deleting the said file. Please ensure that the commits don't break anything. Meanwhile @skmonga you can checkout `2e7221f33d2b7c6e444bdcbf9028eeef7812fadc`, I've verified that it compiles. It does however lack the rebalance feature. I'll keep you posted on this

**Comment by skmonga** [comment] 2018-01-06 19:42
Thanks @aakashkhochare , after changing to the specific version mentioned, I am able to build the project.

**Comment by r-pushkar** [comment] 2018-01-30 09:01
This issue has been resolved with `99ccc8600c`. Closing the issue.

**Closed as completed by r-pushkar** 2018-01-30 09:01 UTC
